### ISSUE TITLE
Push changes to Aliyun China cluster via helm

### ISSUE THREAD

**Issue by Shaun-Harrison** [aliyun/ack-set-context#1]
Hello, 

I'm using this action in an attempt to connect to the my container service cluster in Aliyun 

The action itself seems to run fine, but when it comes to using helm to push the charts to the cluster I get the following error (same actions work elsewhere in GCP so don't believe it's an issue with the helm command)

`Error: Kubernetes cluster unreachable: Get "https://192.168.0.224:6443/version?timeout=32s": dial tcp 192.168.0.224:6443: i/o timeout`

Which to me sounds like the action hasn't actually connected to the cluster?

Any help would be appreciated

**Comment by denverdino** [comment]
@anserhyb can you take a look?

**Comment by Shaun-Harrison** [comment]
Hi @denverdino 

Sorry I completely forgot about this, it was an error on my end, my cluster didn't have an internet end point, closing the issue
